### ISSUE TITLE
Error thrown when a progress bar appears

### ISSUE THREAD

**Issue by yelskiy** [mallowigi/material-theme-jetbrains-eap#203]
### Summary

After updating to 1.3.0 (currently have 1.3.0-beta7) invoking an operation which shows a progress bar results in an error

```bash
com.chrisrm.idea.ui.MTProgressBarUI.getRemainderColor()Ljava/awt/Color;
java.lang.NoSuchMethodError: com.chrisrm.idea.ui.MTProgressBarUI.getRemainderColor()Ljava/awt/Color;
``` 

### Steps to reproduce (if needed)

E.g. For a version-controlled project, modify one or more files, and then proceed to commit changes.

### Environment

GoLand (1.0 Preview) 1.0 EAP
Build #GO-173.3531.21, built on November 2, 2017
GoLand EAP User
Expiration date: December 2, 2017
JRE: 1.8.0_152-release-1024-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.1

### Stack-trace
[stack_trace.txt](https://github.com/mallowigi/material-theme-jetbrains-eap/files/1464887/stack_trace.txt)

**Comment by mallowigi** [comment]
Hmm I know what it is. It's because they modified the progress bars only on recent EAPs, so it doesnt work on older versions...

Rollbacking asap

**Comment by mallowigi** [comment]
Please download the latest version (2290 or 3622 if you're on EAP) and tell me if it fixes

**Comment by yelskiy** [comment]
@mallowigi Thank you!  I've updated, pulling down 173.2290.  Issue appears resolved.
